### ISSUE TITLE
spring-cloud-connectors is deprecated

### ISSUE THREAD

**Issue by dyroberts** [cloudfoundry/java-buildpack-auto-reconfiguration#74] opened 2019-11-29 17:48 UTC
Usage of spring-cloud-connectors is deprecated in favour of java-cfenv.
https://github.com/pivotal-cf/java-cfenv
The module java-cfenv-boot presently includes support for mongodb, cassandra, redis, rabbitmq, and jdbc/datasource. The only thing I can see in java-buildpack-auto-reconfiguration's `CloudServiceReconfigurationBeanFactoryPostProcessor` that isn't directly supported by java-cfenv is javamail. If javamail support was added, it seems like a good chunk of the auto-reconfiguration could be dropped. WDYT?

**Comment by nebhale** [comment] 2020-01-03 18:29
I've struggled with this because it's not a matter of what services are supported so much as what applications are supported.  The big blocker to migrating is that `java-cfenv` (which I love dearly and had a hand in developing) does not support Spring applications, only Spring _Boot_ applications.  Losing this functionality is a serious regression (in the buildpack, not in `java-cfenv`) and I've not yet come to the conclusion that we can break those existing applications.  Eventually we're going to have to as Cloud Connectors ages, but I'm not sure that day is today.

**Comment by dyroberts** [comment] 2020-01-07 13:33
@nebhale Ok, understood! Maybe there's a half-way solution where we could detect boot and add java-cfenv rather than connectors? Barring that, we could detect java-cfenv and skip the connectors reconfiguration step?

**Comment by nebhale** [comment] 2020-01-10 19:26
Maybe something there.  Let me chat with @markpollack about the best way to manage this.

**Comment by dyroberts** [comment] 2020-01-10 21:09
Sounds good! FYI I've taken over maintenance of java-cfenv, ICYMI.

**Comment by dmikusa-pivotal** [comment] 2022-05-27 19:38
Closing. We have begun deprecating Spring Auto Reconfiguration from the buildpack.

https://github.com/cloudfoundry/java-buildpack/issues/779#issuecomment-1084682829

**Closed by dmikusa-pivotal** 2022-05-27 19:38 UTC

**Comment by dev-praveen** [comment] 2024-01-31 11:38
We have a spring boot application (version 1.5.9.RELEASE) that is deployed in PCF and works fine. We are trying to migrate it to java-cfenv-boot library by following the migration guide and removing the dependencies it suggests. However, we encounter a problem with the centralized configuration. The application fails to get the placeholder values from the Spring Cloud Config Server (bound to PCF). 
This is the error we get: [OUT] Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder ‘some.value’ in value “${some.value}”

removed 
org.springframework.boot:spring-boot-starter-cloud-connectors
or
org.springframework.cloud:spring-cloud-core
org.springframework.cloud:spring-cloud-connectors-core
org.springframework.cloud:spring-cloud-cloudfoundry-connector
org.springframework.cloud:spring-cloud-spring-service-connector dependencies from pom file

added 

<dependency>
	<groupId>io.pivotal.cfenv</groupId>
	<artifactId>java-cfenv-boot</artifactId>
	<version>2.4.0</version>
</dependency>

    spring.profiles.active: dev,cloud
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
and we use java_buildpack_offline  Please suggest to fix the issue.

**Comment by dyroberts** [comment] 2024-01-31 15:10
@dev-praveen You should file a new issue. This one's been closed for going-on two years.
