### ISSUE TITLE
Auto-reconfiguration problem with Spring Boot 2.3.0.M1

### ISSUE THREAD

**Issue by anrub** [cloudfoundry/java-buildpack-auto-reconfiguration#75] opened 2020-01-28 11:59 UTC
I can't get the auto-reconfiguration to work with the latest Spring Boot version 2.3.0.M1, following symptoms:

* cloud profile is not set
* bound relational datasource is not used

I used an empty project created by Spring Boot Initializr:
[demo-project-2.3.0.M1.zip](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/files/4122206/demo-project-2.3.0.M1.zip)

For the messages on startup, please see the attached logfile: 
[spring-boot-2.3.0.M1-autoreconfig.txt](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/files/4122194/spring-boot-2.3.0.M1-autoreconfig.txt)

**Comment by scottfrederick** [comment] 2020-01-28 18:59
This is due to [a change in Spring Boot](https://github.com/spring-projects/spring-boot/commit/45b1ab46c37354c9a19cb205dd87cd0ad79dc437) that was intended to ensure a consistent order of class loading. A side-effect of this change is that jar files that were not present at build time but were added by the Java Buildpack are not loaded when the application is started. There is an [issue in Spring Boot](https://github.com/spring-projects/spring-boot/issues/19973) to track this. 

For the features support by auto-reconfiguration, a work-around is to not rely on auto-reconfiguration to configure connections to bound services. Instead, [use Java CFEnv](https://github.com/pivotal-cf/java-cfenv#using-spring-boot) to configure connections. This has the added benefit of giving more control over details of the connection by honoring Spring Boot auto-configuration properties, which is not possible with JBP auto-reconfiguration.

**Comment by scottfrederick** [comment] 2020-02-10 21:04
This issue has been [fixed in Spring Boot](https://github.com/spring-projects/spring-boot/commit/bceed1305f891214ae703dcfbbded5df60d5138c), and will be available in `2.3.0.M2`.

**Closed by scottfrederick** 2020-02-10 21:04 UTC
